language: php

os: linux
dist: focal

php:
    - 7.4
    - 8.0
    - 8.1

env:
    global:
        - XDEBUG_MODE=coverage


notifications:
    email:
        on_success: never

before_script:
    - composer self-update --no-progress --quiet --no-interaction
    - composer update --no-progress --quiet --no-interaction

script:
    - composer run test

after_success: bash <(curl -s https://codecov.io/bash)
